/**
 * Mirror the card colour tokens into src/styles/tokens.css as Tailwind
 * theme variables, so the editor can reference card colours without a
 * second definition. Runs as part of `npm run build`.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { colours, palettes } from '../src/card/tokens.js';

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, '..', 'src', 'styles', 'tokens.css');

const kebab = (s) => s.replace(/[A-Z]/g, (c) => '-' + c.toLowerCase());
const lines = [];
for (const [k, v] of Object.entries(colours)) {
  if (typeof v === 'string') lines.push(`  --color-card-${kebab(k)}: ${v};`);
  else for (const [k2, v2] of Object.entries(v)) lines.push(`  --color-card-${kebab(k)}-${kebab(k2)}: ${v2};`);
}

// One class per palette for the colour swatches, so the page needs no inline styles under the CSP.
const swatches = Object.entries(palettes).map(([id, p]) => `.swatch-${id} { --alert: ${p.alert}; --strip: ${p.condition}; }`);

writeFileSync(
  out,
  `/* Generated by scripts/build-tokens.mjs from src/card/tokens.js. Do not edit. */\n@theme {\n${lines.join('\n')}\n}\n\n${swatches.join('\n')}\n`,
);
console.log(`wrote ${out}`);
